### ISSUE TITLE
[ 01_kubectl ] Logs du container dans le pod

### ISSUE THREAD

**Issue by zepouet** [Treeptik/training-k8s-resources#3]
Je ne comprends pas la réponse à la question 9. Désolé.
Ne manque-t-il pas des options ?

Nicolas

**Comment by minsyslvi** [comment]
Hello : C'est la question qui nécessite peut être des précisions 
Un exemple avec 
1 POD : "auth-replica-5vghh"
Le container dans le POD : "auth"

kubectl logs auth-replica-5vghh auth
2018/06/13 14:49:07 Starting Auth service...
2018/06/13 14:49:07 Health service listening on 0.0.0.0:81
2018/06/13 14:49:07 HTTP service listening on 0.0.0.0:80
