### ISSUE TITLE
[ 05_Service ] - nginx-ingress-controller deployment  CRASHING ? 

### ISSUE THREAD

**Issue by minsyslvi** [Treeptik/training-k8s-resources#4]
Bagarre depuis cet après midi pour saisir le truc et enfin exposer notre "APP"  sur internet .. 
...Sorry les gars mais je ne comprends pas comment le **ingress-nginx-controller** a été déployé - c'est possible de voir cela demain matin avec un cerveau bien frais ? (et si jamais ouvrir une issue "à l'aide au secours Thomas !!"  )  

ingress-nginx "restarting" depuis l'installation de K8s il semble ...
[root@kevinDP-form-k8s-user1-master-1 ~]# kubectl get pods -n ingress-nginx
NAME                                                       READY     STATUS                  RESTARTS   AGE
ingress-nginx-controller-74z98             0/1       CrashLoopBackOff       1683       3d
ingress-nginx-controller-sr25f               0/1       CrashLoopBackOff       1681       3d
ingress-nginx-default-backend-v1.4-jskxn   1/1       Running                  1505       3d
```

**Comment by tperelle** [comment]
Il faut positionner les labels sur les noeuds pour que les ingress-controller démarrent ?
Est-ce que tu l’as fait ?

Thomas PERELLE
